# Generated by Django 3.2.15 on 2023-07-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('online', 'Электронно'), ('not_set', 'Не указанно')], db_index=True, default='not_set', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
