# Generated by Django 3.2.15 on 2023-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230629_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличностью'), ('online', 'Электронно')], db_index=True, default='online', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
